[package]
name = "ip_programmable_erc_1155"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.12.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.20.0" }

[dev-dependencies]
snforge_std = "0.58.0"
assert_macros = "2.12.0"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"
