[sncast.default]
url = "https://starknet-mainnet.g.alchemy.com/starknet/version/rpc/v0_10/5Kaw8bJUF3QFKknr4N6Uo"
account = "mediolano-deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "Voyager"
show-explorer-links = true
